import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/footer";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import { userStore } from "./_redux/store/user.store";
import ReduxStoreProvider from "./lib/reduxStoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <ReduxStoreProvider>
      <html lang="en">

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ToastContainer />
          {children}
          {/* Footer */}
          <Footer />
        </body>
      </html>
    </ReduxStoreProvider>
  );
}
